version: '2'

services:
        wordpress:
                image: wordpress:4.8.3-php7.0-apache
                container_name: wordpress
                ports:
                        - 80
                environment:
                        WORDPRESS_DB_HOST: mysql-server
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: root
                        WORDPRESS_DB_NAME: wordpress
                        VIRTUAL_HOST: technoserver.ddns.net
                volumes:
                        - /home/admin/wp-techno :/var/www/html

        mysql-server:
                image: mysql
                container_name: mysql-server
                environment:
                        MYSQL_ROOT_PASSWORD: root
                volumes:
                        - /home/admin/db_data:/var/lib/mysql

        php-myadmin:
                image: phpmyadmin/phpmyadmin
                container_name: phpmyadmin
                ports:
                        - "5081:80"
                environment:
                        PMA_HOST: mysql-server
                        
networks:
        default:
                external:
                        name: nginx-proxy
        back:
                driver: bridge
