version: "3"
services:
        db:
                image: mysql:latest
                volumes:
                        - db_data:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                container_name: wp_test_db_1
        
        wordpress:
                depends_on: 
                        - db
                image: wordpress:latest
                expose:
                        - 80
                restart: always
                environment:
                        VIRTUAL_HOST: technovikingserver.ddns.net
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
                container_name: wp_test_1
volumes:
        db_data:

networks:
        default:
                external:
                        name: nginx-proxy

